# Generated by Django 4.0.6 on 2022-08-14 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter short caegory name', max_length=155, verbose_name='category title')),
                ('description', models.TextField(help_text='long category description', verbose_name='long description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date category was created', verbose_name='date added')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='comment on reels')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date comment was made', verbose_name='date commented')),
            ],
            options={
                'ordering': ['-date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date dislike was recorded', verbose_name='date disliked')),
            ],
            options={
                'ordering': ['-date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date favorite was added', verbose_name='date favorited')),
            ],
            options={
                'ordering': ['-date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date like was recorded', verbose_name='date liked')),
            ],
            options={
                'ordering': ['-date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for your short video', max_length=255, verbose_name='video title')),
                ('description', models.TextField(help_text='Enter a description for your short video', verbose_name='long description')),
                ('cover_thumbnail', models.FileField(blank=True, help_text='cover image', null=True, upload_to='reels/cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='video cover')),
                ('video', models.FileField(help_text='upload short video file less than 15 minutes', upload_to='reels', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='video file')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, help_text='date video was uploaded', verbose_name='date uploaded')),
            ],
            options={
                'ordering': ['-date_posted', 'title'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date view was made', verbose_name='date viewed')),
                ('real', models.ForeignKey(help_text='reel viewed', on_delete=django.db.models.deletion.CASCADE, to='reel.reel', verbose_name='viewed reel')),
            ],
            options={
                'ordering': ['-date', 'user'],
            },
        ),
    ]
