# Generated by Django 4.0.6 on 2022-08-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='published',
            field=models.BooleanField(default=False, help_text='Designates whether video has been published.', verbose_name='published status'),
        ),
    ]
