# Generated by Django 4.0.6 on 2022-08-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
    ]
